# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{has_breadcrumb}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabriel Sobrinho", "Daniel Lopes", "Nando Vieira"]
  s.date = %q{2010-01-17}
  s.email = %q{gabriel.sobrinho@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "VERSION",
     "examples/images/crumbs.gif",
     "examples/index.html",
     "examples/styles.css",
     "init.rb",
     "lib/breadcrumb.rb",
     "lib/has_breadcrumbs.rb",
     "spec/has_breadcrumbs_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sobrinho/has_breadcrumb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{has_breadcrumbs is a simple plugin that adds a `breadcrumb` object into controllers and views.}
  s.test_files = [
    "spec/has_breadcrumbs_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

